import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import HelloWorld from "./(not-found)/not-found";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WinTicket | Platform",
  description: "Generated by QuynhPTN",
};

export default function NotFound() {
  return <HelloWorld />;
}
